volumes:
  collections_db:
    external: true

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      CORS_HOST: http://localhost:3000
      JWT_SECRET: dzW0qTzFAyo1XvRyvArYUxUYoZTCtxiITGfOYKM6qzrsRYGM8Zuc40BaKRTMCZj7
      DATABASE_URL: mongodb://root:example@mongo:27017/
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  
  mongo:
    image: mongo
    volumes:
      - collections_db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    container_name: ghi
    environment:
      - VITE_API_HOST=http://localhost:8000
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./ghi:/app
    tty: true